### PR TITLE
Added UUID case to GetTypeToPython

### PR DESCRIPTION
**Pull request by maclockard**
Upstream PR here: https://github.com/duckdb/duckdb/pull/5885

### CODE REVIEW

**Comment by maclockard** [comment]
got some upstream feedback, so implementing that

**Review by dylanscott — APPROVED** [review]
thanks for doing this!

it's not very well documented but I think you will want to move or cherry pick this change to be off of the `0.5.1-develop` branch which is branched off of the 0.5.1 release with our changes on top. I can publish a new version to our internal pypi repo once this merges (or you can take a crack at it if you want - there's some documentation [here](https://github.com/hex-inc/duckdb/tree/0.5.1-develop/hexpublish))

**Comment by dylanscott** [comment]
Took the liberty of moving this over to the 0.5.1-develop branch - going to merge now since the builds take a bit to run after merging to build the new artifacts

**Comment by maclockard** [comment]
all good!

**Pull request merged**
